version: '3.7'

services:
  redis:
    image: redis:7
    restart: "always"
    ports:
      - "6379:6379"
    volumes:
      - ./database/redis/config:/usr/local/etc/redis
      - ./database/redis/data:/data
    command: "redis-server"
