name: multithreading_solver
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.6
  - redis=5.0.3
  - click=8.1.7
  - redis-py=5.0.1
  - tqdm=4.66.1
  - pip:
      - python-sat==0.1.8.dev9
      - pyeda=0.28.0
